### ISSUE TITLE
Add Directions

### ISSUE THREAD

**Issue by ayan-b** [sarnava1/MayazKitchen#7]
Using HTML5 Geolocation show the user the location/directions to the restaurant.

**Comment by sarnava1** [comment]
@ayan-b can you please elaborate on this issue so that our contributors can better understand the problem.

**Comment by ayan-b** [comment]
Let's say you are in Kolkata and you want to go to that particular restaurant. So, add a feature to get directions from your location to the restaurant location preferably in a new tab in google maps.

**Comment by ayan-b** [comment]
More info here: https://developers.google.com/maps/documentation/javascript/directions
